adminces.url=http://cestore.ces.com.uy/adminces/
adminces.acceso.password=3)ea60e0be3ba12c6ecd%7297868%5c4
adminces.admin.email=yaniscorrea@gmail.com
adminces.admin.password=12345
adminces.admin.nombre=Yanis
